# Generated by Django 3.2.18 on 2023-03-27 16:41

from django.db import migrations, models
import django.db.models.deletion
import tours.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('passport_series_number', models.CharField(max_length=30, unique=True, verbose_name='Серия и номер паспорта')),
                ('inter_passport_series_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Серия и номер загранпаспорта')),
                ('inter_passport_date', models.DateField(null=True, verbose_name='Дата загранпаспорта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name=models.TextField(max_length=255, verbose_name='Название'))),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_info', models.CharField(max_length=100, verbose_name='Контактная информация')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('rating', models.FloatField(validators=[tours.utils.min_valid], verbose_name='Рейтинг')),
                ('food', models.CharField(max_length=50, verbose_name='Питание')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_id', models.CharField(max_length=255, verbose_name='Идентификатор транспорта')),
                ('start_place', models.CharField(max_length=255, verbose_name='Начальная точка')),
                ('end_place', models.CharField(max_length=255, verbose_name='Конечная точка')),
                ('start_datetime', models.DateTimeField(verbose_name='Начальное время')),
                ('end_datetime', models.DateTimeField(verbose_name='Конечное время')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name=models.CharField(max_length=255, verbose_name='Название'))),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=255, verbose_name='Город/место')),
                ('duration_days', models.IntegerField(verbose_name='длительность (дней)')),
                ('max_adults', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='максимум взрослых')),
                ('max_kids', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='масксимум детей')),
                ('base_price', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='Базовая стоимость')),
                ('need_inter_pass', models.BooleanField(verbose_name='Нужен загранпаспорт')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.hotels', verbose_name='Отель')),
                ('transit_back', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transit_back_relate', to='tours.transit', verbose_name='Транспорт обратно')),
                ('transit_in', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transit_in_relate', to='tours.transit', verbose_name='Транспорт туда')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фото тура',
                'verbose_name_plural': 'Фото туров',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('add_price', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='Добавочная стоимость')),
                ('solo_places', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='одиночных мест')),
                ('twin_places', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='Двойных мест')),
                ('total_places', models.IntegerField(verbose_name='Всего мест')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotels', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Комната в отеле',
                'verbose_name_plural': 'Комнаты в отелях',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_system', models.CharField(max_length=30, verbose_name='Система оплаты')),
                ('card_number', models.CharField(max_length=20, validators=[tours.utils.car_number_valid], verbose_name='Номер карта')),
                ('card_date', models.DateField(validators=[tours.utils.date_valid], verbose_name='Срок карты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Платежная информация',
                'verbose_name_plural': 'Платежная информация',
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotels', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Фото отеля',
                'verbose_name_plural': 'Фото отелей',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=255, verbose_name='Статус опалты')),
                ('adults_count', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='Всего взрослых')),
                ('kids_count', models.IntegerField(validators=[tours.utils.min_valid], verbose_name='Всего детей')),
                ('total_price', models.IntegerField(verbose_name='Общая стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.clients', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.rooms', verbose_name='Комната')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Заказ тура',
                'verbose_name_plural': 'Заказы туров',
            },
        ),
    ]
