# Generated by Django 3.2.18 on 2023-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='inter_passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загранпаспорта'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='slug'),
        ),
    ]
