# Generated by Django 3.2.18 on 2023-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20230327_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='slug'),
        ),
    ]
