# Generated by Django 3.2.18 on 2023-03-30 15:38

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20230328_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=tours.models.tour_photo_location, verbose_name='Изображение'),
        ),
    ]
