# Generated by Django 3.2.18 on 2023-04-01 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0005_tours_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['user'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='login',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='password',
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tours',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=tours.models.tour_main_photo_location, verbose_name='Изображение'),
        ),
    ]
