# Generated by Django 3.2.18 on 2023-04-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20230401_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='inter_passport_date',
        ),
    ]
