# Generated by Django 3.2.18 on 2023-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_clients_inter_passport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='inter_passport_series_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Серия и номер загранпаспорта'),
        ),
    ]
