# Generated by Django 3.2.18 on 2023-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_clients_inter_passport_series_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
