# Generated by Django 3.2.18 on 2023-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_clients_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус опалты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_system',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('МИР', 'МИР')], max_length=30, verbose_name='Система оплаты'),
        ),
    ]
